version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: odoo16
      POSTGRES_USER: odoo16
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - agent_network
      - traefik_public

  odoo:
    image: odoo:16.0-20250311
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./addons-enterprise:/mnt/enterprise-addons
      - ./16.0/init-script.sh:/init-script.sh
      - ./16.0/init-db.sql:/init-db.sql
    user: root
    entrypoint: ["/bin/sh", "-c", "chmod +x /init-script.sh && /init-script.sh"]
    networks:
      - agent_network
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.odoo.rule=Host(`odoo.localhost`)"
        - "traefik.http.routers.odoo.entrypoints=websecure"
        - "traefik.http.routers.odoo.tls.certresolver=le"
        - "traefik.http.services.odoo.loadbalancer.server.port=8069"

volumes:
  odoo-db-data:
    driver: local
  odoo-web-data:
    driver: local

networks:
  traefik_public:
    external: true
    attachable: true
  agent_network:
    external: true
